### ISSUE TITLE
Android draw error with shapes

### ISSUE THREAD

**Issue by rwinright** [wwimmo/react-native-sketch-canvas#10]
When calling the addShape function the first time, the position, size, and location of the shape appears incorrectly on the screen. 

It appears very tiny with thin border edges. 

If you press to draw the shape a second time, it appears correctly.

![Screenshot_1562607129](https://user-images.githubusercontent.com/39418939/60830289-e1f20380-a184-11e9-970f-f8d001912e06.png)

**Comment by creambyemute** [comment]
@rwinright Can you show me how you got there / how you used it in order to reproduce it?

**Comment by rwinright** [comment]
I had tried it on 3 different devices and used both a functional and class component with using it, but kept having the same issues. 

Here’s the code that I implemented it in: 

`const [imageEditorRef, setImageEditorRef] = useState(null);

  return <View style={{ flex: 1, paddingTop: 40 }}>
    <Text>Test_Mode</Text>
    <TouchableOpacity onPress={() => props.updateView("testMode2")}>
      <Text>Go to Recorder</Text>
    </TouchableOpacity>

    <View style={{flexDirection: 'row', justifyContent: 'space-evenly'}}>
      <TouchableOpacity onPress={() => imageEditorRef.addShape({ shapeType: 'Square' })} style={{height: 40, width: 100, backgroundColor: "red", justifyContent: 'center', alignItems: 'center', borderRadius: 80}}>
        <Text style={{color: 'white'}}>Add Square</Text>
      </TouchableOpacity>

      <TouchableOpacity onPress={() => (imageEditorRef.addShape({ shapeType: 'Circle' }))} style={{height: 40, width: 100, backgroundColor: "orange", justifyContent: 'center', alignItems: 'center', borderRadius: 20}}>
        <Text style={{color: 'white'}}>Add Circle</Text>
      </TouchableOpacity>
    </View>

    <RNImageEditor
              ref={ref => setImageEditorRef(ref)}
              touchEnabled={touchEnabled}
              containerStyle={{ backgroundColor: 'transparent', flex: 1 }}
              canvasStyle={{ backgroundColor: 'transparent', flex: 1 }}
              onStrokeEnd={data => {
                console.log(data)
              }}
              // closeComponent={<View style={styles.functionButton}><Text style={{ color: 'white' }}>Close</Text></View>}
              // onClosePressed={() => {
              //   setExample(0);
              // }}
              undoComponent={<View style={styles.functionButton}><Text style={{ color: 'white' }}>Undo</Text></View>}
              // clearComponent={<View style={styles.functionButton}><Text style={{ color: 'white' }}>Clear</Text></View>}
              // onClearPressed={() => {
              //   // this.canvas.decreaseSelectedShapeFontsize();
              //   // this.canvas.increaseSelectedShapeFontsize();
              //   // this.canvas.changeSelectedShapeText("Random text " + Math.random());
              //   // Alert.alert('do something')
              // }}
              // onUndoPressed={(id) => {
                // imageEditorRef.addShape({ shapeType: 'Circle' });
                // this.canvas.addShape({ shapeType: 'Rect' });
                // this.canvas.addShape({ shapeType: 'Square' });
                // this.canvas.addShape({ shapeType: 'Triangle' });
                // this.canvas.addShape({ shapeType: 'Arrow' });
                // this.canvas.addShape({ shapeType: 'Text', textShapeFontSize: 10, textShapeText: "Added TextShape from JS" });
                // this.canvas.addShape({ shapeType: 'Text', textShapeFontType: 'fonts/IndieFlower.ttf', textShapeFontSize: 5, textShapeText: "Added TextShape with custom TypeFace" });
                // Alert.alert('do something')
              // }}
              // clearComponent={<View style={styles.functionButton}><Text style={{ color: 'white' }}>Clear</Text></View>}
              // onClearPressed={() => {
              //   // this.canvas.decreaseSelectedShapeFontsize();
              //   // this.canvas.increaseSelectedShapeFontsize();
              //   // this.canvas.changeSelectedShapeText("Random text " + Math.random());
              //   // Alert.alert('do something')
              // }}
              eraseComponent={<View style={styles.functionButton}><Text style={{ color: 'white' }}>Eraser</Text></View>}
              deleteSelectedShapeComponent={<View style={styles.functionButton}><Text style={{ color: 'white' }}>Delete</Text></View>}
              strokeComponent={color => (
                <View style={[{ backgroundColor: color }, styles.strokeColorButton]} />
              )}
              // strokeSelectedComponent={(color, index, changed) => {
              //   return (
              //     <View style={[{ backgroundColor: color, borderWidth: 2 }, styles.strokeColorButton]} />
              //   )
              // }}
              // strokeWidthComponent={(w) => {
              //   return (<View style={styles.strokeWidthButton}>
              //     <View style={{
              //       backgroundColor: 'white', marginHorizontal: 2.5,
              //       width: Math.sqrt(w / 3) * 10, height: Math.sqrt(w / 3) * 10, borderRadius: Math.sqrt(w / 3) * 10 / 2
              //     }} />
              //   </View>
              //   )
              // }}
              defaultStrokeIndex={0}
              defaultStrokeWidth={5}
              saveComponent={<View style={styles.functionButton}><Text style={{ color: 'white' }}>Save</Text></View>}
              savePreference={() => {
                return {
                  folder: "RNImageEditor",
                  filename: String(Math.ceil(Math.random() * 100000000)),
                  transparent: false,
                  imageType: "png"
                }
              }}
              onSketchSaved={(success, path) => {
                Alert.alert(success ? 'Image saved!' : 'Failed to save image!', path)
              }}
              // onPathsChange={(pathsCount) => {
              //   console.log('pathsCount', pathsCount)
              // }}
              onShapeSelectionChanged={(isShapeSelected) => {
                setTouchEnabled( prevState => !isShapeSelected )
              }}
              shapeConfiguration={{ shapeBorderColor: 'black', shapeBorderStyle: 'Dashed', shapeBorderStrokeWidth: 1 }}
            />

  </View>`

**Comment by creambyemute** [comment]
@rwinright I remember having run into this issue as well in the past but thought I had "fixed" it.
It's most likely related to the following code snippet apparent in every add*Entity function in the java implementation:
```
        if (mSketchCanvas.getWidth() < 100 || mSketchCanvas.getHeight() < 100) {
            circleEntity = new CircleEntity(circleLayer, mDrawingCanvas.getWidth(), mDrawingCanvas.getHeight(), 300, 20f, mEntityStrokeWidth, mEntityStrokeColor);
        } else {
            circleEntity = new CircleEntity(circleLayer, mSketchCanvas.getWidth(), mSketchCanvas.getHeight(), 300, 20f, mEntityStrokeWidth, mEntityStrokeColor);
        }
```

**Comment by rwinright** [comment]
Thank you for this! I’m going to leave the issue open until I have the opportunity to jump back into this project on Monday! :)

**Comment by rwinright** [comment]
I have been playing around with the code snippets you had said I should look at. 

I have a suspicion that the mDrawingCanvas is being rendered at a default width of 105px or so and the shapes are being drawn on top of that canvas instead of the sketch canvas itself? 

I simply changed `mSketchCanvas.getWidth() < 100 || mSketchCanvas.getHeight() < 100` to `mSketchCanvas.getWidth() < 110 || mSketchCanvas.getHeight() < 110` and it seems to be working perfectly thus far. 

I wouldn’t say that it’s the best fix from my end as there obviously must have been a reason for the original code, but it’s working great for the time being.
