### ISSUE TITLE
Android openImageFile() bug

### ISSUE THREAD

**Issue by tensfeld** [wwimmo/react-native-sketch-canvas#11]
Hi. I think this should be "convertedDirectory + filename" instead. Can I pull a request to fix that?

https://github.com/wwimmo/react-native-sketch-canvas/blob/ac886a7d91fdeb2f1c69329fe9fdeba36c2e8f89/android/src/main/java/com/wwimmo/imageeditor/ImageEditor.java#L467

**Comment by creambyemute** [comment]
@tensfeld Thank you for your contributions!
