### ISSUE TITLE
Programmatically select shape

### ISSUE THREAD

**Issue by DaniyarJakupov** [wwimmo/react-native-sketch-canvas#18]
Hello,

Is there a way to select already added shape programmatically? Since `undo` method is not removing shapes by default, the only way to remove them is to call ` this.canvas.deleteSelectedShape()`. But it only deletes if the shape is manually selected

**Comment by creambyemute** [comment]
@DaniyarJakupov In theory, yes. But it's not exposed and you would not have the needed information to tell the native code which shape to select.

In the native Android/iOS code there is a `selectEntity(MotionEntity entity)` and `findEntityAtPoint(float x, float y)` method.

Feel free to provide a PR for this as atm I'm busy with something else.

**Comment by DaniyarJakupov** [comment]
Understood. Unfortunately, we cannot use this library. But if I come back to it in the future, I'll try to make some contributions. Thank you!
