### ISSUE TITLE
getPaths() of pre-defined shapes is not correct

### ISSUE THREAD

**Issue by DaniyarJakupov** [wwimmo/react-native-sketch-canvas#19]
Hi,

There is a problem with getting a path of pre-defined shapes. When you add arrow to canvas, then try to get its path, the following result is returned:

```
path: { data: [0: '266, 253.5']  }
``` 

There is just a single point returned. The same happens with other shapes. In my case, the path is crucial, since that's how we sync drawings between web/mobile. 
Is there a way to get a full path of added  on canvas shapes?

**Comment by creambyemute** [comment]
@DaniyarJakupov Unfortunately the shapes are not paths anymore when rendered but Bitmaps on Android and UIViews rendered into context/added as subviews on iOS.

**Comment by DaniyarJakupov** [comment]
Ok, I see. Thank you for the library anyway!
