### ISSUE TITLE
Mirror Shape Movement

### ISSUE THREAD

**Issue by ajnozari** [wwimmo/react-native-sketch-canvas#8]
I'm trying to mirror shapes and for some reason they are not moving on the other screen.  I disable touch when the shape is selected, but I can't find the function that triggers the shape to move.  Again if you point me in the right direction I should be able to figure this out and make it work but at a wall atm.

thank you for any help in advanced.

**Comment by creambyemute** [comment]
@ajnozari Did you find a solution?
I'm not sure I understand what you wanted to achieve exactly:

Did you want to add shapes to one canvas and they should be mirrored onto a second canvas? If so, i've never tested this if it actually works.

**Comment by ajnozari** [comment]
Thank you for closing this, I was able to do what I needed.
